### ISSUE TITLE
Strong naming an assembly doesn't update the pdb hash

### ISSUE THREAD

**Issue by niemyjski** [oising/strongnaming#8]
I'm trying to sign our assemblies without doing a full rebuild but I'm running into errors when I try to submit our signed nuget package to symbol source.

Package submission failed: Incorrect hash code for Exceptionless.Console binaryHash symbolHash ED901068EDCF40AF8A33BA270CE93B861

**Comment by oising** [comment]
I'll look into this. Thanks. (been busy the lats few months)

**Comment by oising** [comment]
Hmm, it appears modifying the PDB is extremely non-trivial. I don't think I could make this work in any reasonable amount of time. I'll have to close this as "Won't fix." In the meantime, if you disable "require source files to exactly match the original versions" in Visual Studio (tools > options > debugging) I believe you can bypass this issue.

**Comment by niemyjski** [comment]
It wasn't really not that non-trivial I tried a million things and couldn't get it to work. I ended up giving up and just recompiling the whole project multiple times.
